apiVersion: v1
kind: Secret

metadata:
  name: app-secrets
  namespace: ai-task-platform

type: Opaque

stringData:
  jwt-secret: "production_super_secret_key_change_me"

  mongo-uri: "mongodb+srv://b210093_db_user:iidVYjcx7vK794FK@cluster0.xyitwlh.mongodb.net/ai-tasks?appName=Cluster0"